### PR TITLE
Add support for namespaced models

### PR DESCRIPTION
**Pull request by thijsvdanker**
The current implementation does not support the use of nested namespaces like 

- App\Models\Foo\Recipe
- App\Models\Bar\Group

This PR tweaks the getting the FactoryName from a model by using a new config variable `factories-reloaded.models_namespace` and deriving the factory name based on the difference between the base namespace and the passed in model.

The config variable should be set to the **base** namespace for the models.
In my example this would be

```php
    'models_namespace' => 'App\Models',
```

This PR does need some addition to the Readme and it is a **breaking change** as it introduces a new config variable that is required.

### CODE REVIEW

**Comment by christophrumpel** [comment]
Good idea @thijsvdanker, can you give the error another look? I will take a look at the PR later today or tomorrow 👍

**Comment by thijsvdanker** [comment]
I've fixed the first failure, it's hanging on a migration now.
I'll try to look into it later today.

**Comment by thijsvdanker** [comment]
@christophrumpel I just don't see it... I have no clue why the migration is not being run in the tests.
Do you have any idea?

**Comment by christophrumpel** [comment]
Oh I didn't see your comment. Will check it what's going on here.

**Comment by christophrumpel** [comment]
Did the tests work for you locally?

**Comment by christophrumpel** [comment]
We just added a new feature where you can define multiple model paths in the config. This way people with DDD design can define their models there as well. This is probably a more convenient way to support that. Still thanks for your work. I hope you like the new features.

**Comment by thijsvdanker** [comment]
Looks great!

**Pull request closed without merging**
